### ISSUE TITLE
Mac error after restart

### ISSUE THREAD

**Issue by AlexsanderShaw** [x-Ai/BurpSuite#26]
Hi, thx first. When I active it first time, it works well. But when I restart my MacBook Pro 2019, it reports error:
<img width="260" alt="image" src="https://github.com/x-Ai/BurpSuite/assets/18108607/f283a662-0a50-45b7-a9b8-db10c31bfcfa">

My os version is MacOS 13, and
My java version is :
`java 17.0.6 2023-01-17 LTS
Java(TM) SE Runtime Environment (build 17.0.6+9-LTS-190)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.6+9-LTS-190, mixed mode, sharing)`

And method I can fix it?

**Comment by x-Ai** [comment]
please provide more detailed information, so far, it's not the loader that's the problem

**Comment by nanshihui** [comment]
same as me

**Comment by hunter-tp** [comment]
I've encountered this issue as well, and here's how I solved it：
1. open /Applications/Burp Suite Professional.app/Contents/Info.plist
2. delete the previously added config
![image](https://github.com/x-Ai/BurpSuite/assets/8099544/2c58bdf3-381c-4230-9f9f-f7e277778d9c)
3. now you can open Burp normally.
4. Close Burp and once again add the deleted content to Info.plist
5. now everything is ok 😄
Finally, I suspect the issue was caused by Burp's automatic update altering something, so I've turned off automatic updates.
![image](https://github.com/x-Ai/BurpSuite/assets/8099544/10a0df64-8491-40a5-b8be-9cb8c22e705f)
